### ISSUE TITLE
GridToPager doesn't handle device rotation

### ISSUE THREAD

**Issue by carsonb** [google/android-transition-examples#1]
The example works great if the device remains in one orientation during the demo, but unfortunately not if rotation is added to the mix.

If the user rotates the device after the transition, there is no animation on return. Moreover, if the device begins in portrait, transitions to the paged view, rotates to landscape, then back to portrait, animated transition back to the grid is lost.

**Comment by Shalom** [comment]
Thanks for reporting this! 
Fixed at https://github.com/google/android-transition-examples/commit/6910b1ff673c1abdeff9515d97c41b34f7ee2efc.

**Comment by carsonb** [comment]
Thanks!

**Comment by iomagics** [comment]
Unfortunately, this creates another issue. It seems to be tied with the OnLayoutChangeListener.
The position will only be saved if an ImageFragment is displaying, you rotate the device, and navigate back to the GridFragment. However, if you rotate the device when you are back in the GridFragment the LayoutManager will restore the same state from when you rotated the device in the ImageFragment.

Replicate: 
* Scroll halfway down the list, select an image, and rotate the device.
* Navigate back to the grid, scroll all the way down and rotate the device. 

The list will be at the same position as it was when navigating back from the ImageFragment.

I have been trying to find a way to get the OnLayoutChangeListener to notice when it's called due to a configuration change. But I'm still unsuccessful. I will post here if I find a solution.

Edit: Found a solution to the bug. I made a pull request. Do what you want with it :)
#5
